name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # 触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许写入GitHub Pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Vue2推荐使用Node 16

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # 执行package.json中的build脚本

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Vue CLI默认输出目录
          keep_files: false # 清理旧文件
